#!/usr/bin/env python3
"""Keep every restatement of the palette and the tag policy in step.

Two kinds of consumer, handled two ways:

  GENERATED  TypeScript modules are derived wholesale from the JSON. They are
             checked in (the frontend tree has to build on its own — only
             ``frontend/dist`` ships, not the repo) but never hand-edited.

  CHECKED    app.css, offline.html, index.html, favicon.svg, vite.config.ts and
             BrandMark.svelte stay hand-authored — they are design surfaces, and
             a generator writing into them would be worse than the drift. Instead
             each literal is asserted against the JSON, by name, with the line it
             was found on.

Why this exists: the palette was changed in one pass and three different brand
blues shipped simultaneously — the favicon, the manifest and the runtime
theme-color each held their own copy. Nothing failed; it just looked wrong.

    python3 tools/design/sync_tokens.py            # check, exit 1 on drift
    python3 tools/design/sync_tokens.py --write    # regenerate, then check
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import NamedTuple

REPO = Path(__file__).resolve().parents[2]
TOKENS_JSON = REPO / "shared" / "design_tokens.json"
TAXONOMY_JSON = REPO / "shared" / "taxonomy.json"

GEN_TOKENS_TS = REPO / "frontend" / "src" / "lib" / "designTokens.ts"
GEN_TAXONOMY_TS = REPO / "frontend" / "src" / "lib" / "taxonomy.generated.ts"

BANNER = "// GENERATED by tools/design/sync_tokens.py — do not edit.\n// Source: shared/%s\n"


# --------------------------------------------------------------------------- #
# Checked files.
#
# Each entry is one place the palette is restated outside the JSON. The regex is
# deliberately narrow — it pins the literal to its surrounding declaration, so a
# match failure means "that declaration moved", not "some hex changed".
#
# `scope` slices the file before searching, because app.css declares the same
# custom property once per theme; without it the light check reads the dark
# block's value. Every match inside the scope must equal the token.
# --------------------------------------------------------------------------- #
class Check(NamedTuple):
    rel: str
    token: str
    mode: str
    pattern: str
    scope: str | None = None  # regex; the search runs from its match to the next


# app.css declares the palette twice; anchor each half.
LIGHT_BLOCK = r"^:root,"
DARK_BLOCK = r"^\[data-theme='dark'\]"

_APP_CSS_LIGHT = [
    ("accent", r"--accent:\s*(#[0-9a-fA-F]{6})"),
    ("primary", r"--primary:\s*(#[0-9a-fA-F]{6})"),
    ("surface", r"--surface:\s*(#[0-9a-fA-F]{6})"),
    ("panel", r"--panel:\s*(#[0-9a-fA-F]{6})"),
    ("on-surface", r"--on-surface:\s*(#[0-9a-fA-F]{6})"),
    ("muted", r"--muted:\s*(#[0-9a-fA-F]{6})"),
    ("subtle", r"--subtle:\s*(#[0-9a-fA-F]{6})"),
    ("border", r"--border:\s*(#[0-9a-fA-F]{6})"),
]

CHECKS: list[Check] = [
    # app.css is the design surface: assert it agrees with the JSON rather than
    # generating it, so the palette stays editable in one readable place.
    *(Check("frontend/src/app.css", name, "light", pat, LIGHT_BLOCK) for name, pat in _APP_CSS_LIGHT),
    Check("frontend/src/app.css", "theme-color", "dark", r"--app-bar:\s*(#[0-9a-fA-F]{6})", DARK_BLOCK),
    # The offline page ships before any stylesheet, so it inlines its own copy.
    Check("frontend/public/offline.html", "surface", "light", r"--surface:\s*(#[0-9a-fA-F]{6})"),
    Check("frontend/public/offline.html", "on-surface", "light", r"--on-surface:\s*(#[0-9a-fA-F]{6})"),
    Check("frontend/public/offline.html", "muted", "light", r"--muted:\s*(#[0-9a-fA-F]{6})"),
    Check("frontend/public/offline.html", "primary", "light", r"--primary:\s*(#[0-9a-fA-F]{6})"),
    Check("frontend/public/offline.html", "accent", "light", r"--accent:\s*(#[0-9a-fA-F]{6})"),
    Check("frontend/public/offline.html", "panel", "light", r"--panel:\s*(#[0-9a-fA-F]{6})"),
    Check("frontend/public/offline.html", "border", "light", r"--border:\s*(#[0-9a-fA-F]{6})"),
    Check(
        "frontend/public/offline.html",
        "theme-color",
        "light",
        r'name="theme-color"\s+content="(#[0-9a-fA-F]{6})"',
    ),
    # Browser chrome tint on first paint, before theme.ts runs.
    Check(
        "frontend/index.html",
        "theme-color",
        "light",
        r'name="theme-color"\s+content="(#[0-9a-fA-F]{6})"',
    ),
    # The mark, in two renderings that must not drift apart. It is an ink
    # ground with the accent as a foot rule, so each part is pinned by id.
    Check("frontend/public/favicon.svg", "on-surface", "light",
          r'id="ground"[^>]*fill="(#[0-9a-fA-F]{6})"'),
    Check("frontend/public/favicon.svg", "accent", "light",
          r'id="rule"[^>]*fill="(#[0-9a-fA-F]{6})"'),
    Check("frontend/public/favicon.svg", "panel", "light",
          r'<path[^>]*fill="(#[0-9a-fA-F]{6})"'),
    Check("frontend/src/components/BrandMark.svelte", "on-surface", "light",
          r"background:\s*(#[0-9a-fA-F]{6})"),
    Check("frontend/src/components/BrandMark.svelte", "panel", "light",
          r"color:\s*(#[0-9a-fA-F]{6})"),
    Check("frontend/src/components/BrandMark.svelte", "accent", "light",
          r'<rect[^>]*fill="(#[0-9a-fA-F]{6})"'),
    # PWA manifest — the install banner and splash screen.
    Check("frontend/vite.config.ts", "theme-color", "light", r"theme_color:\s*'(#[0-9a-fA-F]{6})'"),
    Check("frontend/vite.config.ts", "surface", "light", r"background_color:\s*'(#[0-9a-fA-F]{6})'"),
]


def check_files(tokens: dict[str, dict[str, str]]) -> list[str]:
    problems: list[str] = []
    for check in CHECKS:
        path = REPO / check.rel
        if not path.exists():
            problems.append(f"{check.rel}: missing (referenced by a token check)")
            continue
        text = path.read_text(encoding="utf-8")
        entry = tokens.get(check.token)
        if entry is None:
            problems.append(f"{check.rel}: unknown token {check.token!r}")
            continue
        want = (entry.get(check.mode) or entry.get("light", "")).lower()

        # Narrow to the scoped block, keeping the offset so line numbers stay
        # true to the whole file.
        base = 0
        haystack = text
        if check.scope:
            anchor = re.search(check.scope, text, re.MULTILINE)
            if anchor is None:
                problems.append(f"{check.rel}: scope {check.scope!r} not found")
                continue
            base = anchor.start()
            nxt = re.search(r"^\}", text[anchor.end() :], re.MULTILINE)
            end = anchor.end() + (nxt.end() if nxt else len(text) - anchor.end())
            haystack = text[base:end]

        found = [(base + m.start(), m.group(1).lower()) for m in re.finditer(check.pattern, haystack)]
        if not found:
            problems.append(f"{check.rel}: no match for {check.token} ({check.mode}) — pattern {check.pattern!r}",
            )
            continue
        for offset, got in found:
            if got != want:
                line = text.count("\n", 0, offset) + 1
                problems.append(f"{check.rel}:{line}: {check.token} ({check.mode}) is {got}, expected {want}",
                )
    return problems


def render_tokens_ts(tokens: dict[str, dict[str, str]]) -> str:
    lines = [
        BANNER % "design_tokens.json",
        "//\n",
        "// The palette values that exist outside app.css. TypeScript needs them\n",
        "// where a CSS custom property can't reach — setting <meta theme-color>,\n",
        "// or painting into a canvas.\n\n",
        "export const designTokens = {\n",
    ]
    for name, entry in tokens.items():
        role = entry.get("role")
        if role:
            lines.append(f"  /** {role} */\n")
        modes = ", ".join(
            f"{m}: '{entry[m]}'" for m in ("light", "dark") if m in entry
        )
        lines.append(f"  '{name}': {{ {modes} }},\n")
    lines.append("} as const\n\n")
    lines.append("export type DesignToken = keyof typeof designTokens\n\n")
    lines.append(
        "/** Hex for a token, falling back to the light step when there is no dark one. */\n"
        "export function designToken(name: DesignToken, mode: 'light' | 'dark' = 'light'): string {\n"
        "  const entry = designTokens[name] as { light: string; dark?: string }\n"
        "  return (mode === 'dark' && entry.dark) || entry.light\n"
        "}\n"
    )
    return "".join(lines)


def render_taxonomy_ts(data: dict[str, object]) -> str:
    meta = sorted(str(t).strip().lower() for t in data["meta_tags"])  # type: ignore[union-attr]
    labels: dict[str, str] = {
        str(k).lower(): str(v) for k, v in data["display_labels"].items()  # type: ignore[union-attr]
    }
    out = [
        BANNER % "taxonomy.json",
        "//\n",
        f"// {data['meta_tags_note']}\n\n",
        "export const META_TAGS: ReadonlySet<string> = new Set([\n",
    ]
    out += [f"  '{t}',\n" for t in meta]
    out.append("])\n\n")
    out.append(f"// {data['display_labels_note']}\n")
    out.append("export const DISPLAY_LABELS: Readonly<Record<string, string>> = {\n")
    out += [f"  '{k}': '{v}',\n" for k, v in sorted(labels.items())]
    out.append("}\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="regenerate the TS modules")
    args = ap.parse_args()

    tokens = json.loads(TOKENS_JSON.read_text(encoding="utf-8"))["tokens"]
    taxonomy = json.loads(TAXONOMY_JSON.read_text(encoding="utf-8"))

    wanted = {GEN_TOKENS_TS: render_tokens_ts(tokens), GEN_TAXONOMY_TS: render_taxonomy_ts(taxonomy)}

    problems: list[str] = []
    for path, content in wanted.items():
        rel = path.relative_to(REPO)
        if args.write:
            path.write_text(content, encoding="utf-8")
            print(f"wrote {rel}")
        elif not path.exists() or path.read_text(encoding="utf-8") != content:
            problems.append(f"{rel}: stale — run `python3 tools/design/sync_tokens.py --write`")

    problems += check_files(tokens)

    if problems:
        print("design token drift:", file=sys.stderr)
        for p in problems:
            print(f"  {p}", file=sys.stderr)
        return 1
    print("design tokens and tag policy are in sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
