// GENERATED by tools/design/sync_tokens.py — do not edit.
// Source: shared/design_tokens.json
//
// The palette values that exist outside app.css. TypeScript needs them
// where a CSS custom property can't reach — setting <meta theme-color>,
// or painting into a canvas.

export const designTokens = {
  /** Brand mark foot rule. The one blue the logo is drawn in. */
  'accent': { light: '#4a5bd0' },
  /** Link ink — indigo darkened to clear WCAG AA on --surface. */
  'primary': { light: '#3a49ad' },
  /** Daylight page background. Cool paper, the night surface inverted. */
  'surface': { light: '#eef0f5' },
  /** Raised paper / glyph fill on the stamp. */
  'panel': { light: '#f7f8fc' },
  /** Headline ink and stamp ground. */
  'on-surface': { light: '#14161c' },
  /** Secondary text: bylines, timestamps, breadcrumbs. */
  'muted': { light: '#5a5e6a' },
  /** Tertiary marks: breadcrumb separators, hairline glyphs. */
  'subtle': { light: '#767b88' },
  /** Hairline rules. */
  'border': { light: '#d4d7e0' },
  /** Browser/OS chrome tint. Matches the page, not an inverted bar. */
  'theme-color': { light: '#eef0f5', dark: '#0f1117' },
} as const

export type DesignToken = keyof typeof designTokens

/** Hex for a token, falling back to the light step when there is no dark one. */
export function designToken(name: DesignToken, mode: 'light' | 'dark' = 'light'): string {
  const entry = designTokens[name] as { light: string; dark?: string }
  return (mode === 'dark' && entry.dark) || entry.light
}
