// GENERATED by tools/design/sync_tokens.py — do not edit.
// Source: shared/design_tokens.json
//
// The palette values that exist outside app.css. TypeScript needs them
// where a CSS custom property can't reach — setting <meta theme-color>,
// or painting into a canvas.

export const designTokens = {
  /** Brand mark and interaction. The one blue the logo is drawn in. */
  'accent': { light: '#4a5bd0' },
  /** Link ink — accent darkened to clear WCAG AA on --surface. */
  'primary': { light: '#3a49ad' },
  /** Warm newsprint page background. */
  'surface': { light: '#f7f4ee' },
  /** Raised card / app-bar fill. */
  'panel': { light: '#fffdf8' },
  /** Headline ink. */
  'on-surface': { light: '#171410' },
  /** Secondary text: bylines, timestamps, breadcrumbs. */
  'muted': { light: '#6a6355' },
  /** Tertiary marks: breadcrumb separators, hairline glyphs. */
  'subtle': { light: '#7d7566' },
  /** Hairline rules. */
  'border': { light: '#e0d9cb' },
  /** Browser/OS chrome tint. Light tints to brand; dark matches --app-bar. */
  'theme-color': { light: '#3a49ad', dark: '#141210' },
} as const

export type DesignToken = keyof typeof designTokens

/** Hex for a token, falling back to the light step when there is no dark one. */
export function designToken(name: DesignToken, mode: 'light' | 'dark' = 'light'): string {
  const entry = designTokens[name] as { light: string; dark?: string }
  return (mode === 'dark' && entry.dark) || entry.light
}
