// GENERATED by tools/design/sync_tokens.py — do not edit.
// Source: shared/taxonomy.json
//
// Provenance and pipeline labels. Fine as chips at the end of an article; never the kicker, because they say how we found the story rather than what it is about.

export const META_TAGS: ReadonlySet<string> = new Set([
  'ai',
  'algorand',
  'blockchain',
  'chain',
  'chain-only',
  'digest',
  'discord',
  'discovery',
  'generic',
  'mail',
  'news',
  'on-chain',
  'onchain',
  'service',
  'telegram',
  'update',
  'updated',
  'web',
  'weekly',
])

// Internal slug -> reader-facing text. DISPLAY ONLY: /topic/<tag> URLs always use the raw slug on both sides, so a link never changes shape based on this table.
export const DISPLAY_LABELS: Readonly<Record<string, string>> = {
  'chain-only': 'on-chain',
}
